<?php
$pageTitle='Contact';$theme='pink';$success='';$errors=[];$selected=trim($_GET['service']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){
$name=trim($_POST['name']??'');$phone=trim($_POST['phone']??'');$email=trim($_POST['email']??'');$type=trim($_POST['service_type']??'');$message=trim($_POST['message']??'');
if($name===''||$phone===''||$type===''||$message==='')$errors[]='Please complete all required fields.';
if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Please enter a valid email.';
if(!$errors){$sid=null;$s=$pdo->prepare("SELECT id FROM services WHERE name=? LIMIT 1");$s->execute([$type]);$sid=$s->fetchColumn()?:null;$q=$pdo->prepare("INSERT INTO inquiries(service_id,name,phone,email,service_type,message) VALUES(?,?,?,?,?,?)");$q->execute([$sid,$name,$phone,$email,$type,$message]);$pdo->prepare('INSERT INTO notifications(title,message,type) VALUES(?,?,?)')->execute(['New customer inquiry',$name.' submitted an inquiry for '.$type,'inquiry']);$success='Thank you! Your inquiry has been received.';}
}
include 'includes/header.php'; ?>
<section class="py-5"><div class="container"><div class="row g-5"><div class="col-lg-5"><h2>Let's plan your celebration.</h2><p class="text-muted">Tell us what you need and our team will get back to you.</p><a class="btn btn-success" target="_blank" href="https://wa.me/923158118810"><i class="bi bi-whatsapp me-2"></i>WhatsApp 0315 8118810</a></div><div class="col-lg-7"><div class="content-card p-4"><?php if($success): ?><div class="alert alert-success"><?= htmlspecialchars($success) ?></div><?php endif; ?><?php foreach($errors as $e): ?><div class="alert alert-danger"><?= htmlspecialchars($e) ?></div><?php endforeach; ?><form method="post" class="needs-validation" novalidate><div class="row g-3"><div class="col-md-6"><label class="form-label">Name *</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Phone *</label><input name="phone" class="form-control" required></div><div class="col-12"><label class="form-label">Email *</label><input name="email" type="email" class="form-control" required></div><div class="col-12"><label class="form-label">Service *</label><select name="service_type" class="form-select" required><option value="">Choose a service</option><?php foreach($pdo->query("SELECT name FROM services ORDER BY name") as $s): ?><option <?= $selected===$s['name']?'selected':'' ?>><?= htmlspecialchars($s['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Message *</label><textarea name="message" rows="5" class="form-control" required></textarea></div><div class="col-12"><button class="btn btn-brand">Send Inquiry</button></div></div></form></div></div></div></div></section>
<?php include 'includes/footer.php'; ?>
