<?php
$pageTitle='Plan My Event';$theme='pink';require_once 'includes/user-auth.php';
$plan=null;$errors=[];$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
$name=trim($_POST['name']??'');$type=trim($_POST['event_type']??'');$date=$_POST['event_date']??null;$area=(int)($_POST['area_id']??0);$guests=max(0,(int)($_POST['guests']??0));$budget=max(0,(float)($_POST['budget']??0));$notes=trim($_POST['notes']??'');
if($name===''||$type===''||!$date||$budget<=0)$errors[]='Please complete your name, event type, date and budget.';
if(!$errors){$q=$pdo->prepare('INSERT INTO event_plans(user_id,name,event_type,event_date,area_id,guests,budget,notes) VALUES(?,?,?,?,?,?,?,?)');$q->execute([$_SESSION['user_id']??null,$name,$type,$date,$area?:null,$guests,$budget,$notes]);$id=$pdo->lastInsertId();$plan=['id'=>$id,'name'=>$name,'type'=>$type,'date'=>$date,'guests'=>$guests,'budget'=>$budget];$success='Your event plan was saved. Here is a suggested budget package.';}
}
include 'includes/header.php';
$areas=$pdo->query('SELECT * FROM areas WHERE active=1 ORDER BY name')->fetchAll();
?>
<section class="py-5"><div class="container"><div class="row g-5 align-items-start"><div class="col-lg-5"><p class="eyebrow">SMART EVENT PLANNER</p><h2>Plan your celebration around your budget.</h2><p class="text-muted">Tell us your event details and Quetta Celebrations Hub will suggest a practical package you can refine with vendors.</p><div class="content-card p-4"><div class="d-flex gap-3 mb-3"><i class="bi bi-calendar-heart fs-2" style="color:var(--pink)"></i><div><b>1. Tell us your event</b><div class="small text-muted">Date, guests, area and budget.</div></div></div><div class="d-flex gap-3 mb-3"><i class="bi bi-pie-chart fs-2" style="color:var(--pink)"></i><div><b>2. Get a suggested plan</b><div class="small text-muted">See estimated spending by category.</div></div></div><div class="d-flex gap-3"><i class="bi bi-people fs-2" style="color:var(--pink)"></i><div><b>3. Contact vendors</b><div class="small text-muted">Use the marketplace to request bookings.</div></div></div></div></div>
<div class="col-lg-7"><div class="content-card p-4 p-md-5"><?php foreach($errors as $e): ?><div class="alert alert-danger"><?=htmlspecialchars($e)?></div><?php endforeach;?><?php if($success): ?><div class="alert alert-success"><?=htmlspecialchars($success)?></div><?php endif;?><form method="post" class="needs-validation" novalidate><div class="row g-3"><div class="col-md-6"><label class="form-label">Your Name *</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Event Type *</label><select name="event_type" class="form-select" required><option value="">Choose</option><option>Wedding</option><option>Birthday</option><option>Engagement</option><option>Baby Shower</option><option>Corporate Event</option><option>Anniversary</option><option>Proposal</option></select></div><div class="col-md-6"><label class="form-label">Event Date *</label><input type="date" name="event_date" class="form-control" required></div><div class="col-md-6"><label class="form-label">Quetta Area</label><select name="area_id" class="form-select"><option value="0">Choose area</option><?php foreach($areas as $a):?><option value="<?=$a['id']?>"><?=htmlspecialchars($a['name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Guests</label><input type="number" min="1" name="guests" class="form-control" placeholder="e.g. 150"></div><div class="col-md-6"><label class="form-label">Total Budget (PKR) *</label><input type="number" min="1" name="budget" class="form-control" required placeholder="150000"></div><div class="col-12"><label class="form-label">Special Requirements</label><textarea name="notes" class="form-control" rows="3" placeholder="Theme, venue preference, colors, etc."></textarea></div><div class="col-12 d-grid"><button class="btn btn-brand btn-lg"><i class="bi bi-magic me-2"></i>Create My Event Plan</button></div></div></form>
<?php if($plan): $b=$plan['budget'];$items=[['Decoration',.28],['Photography & Video',.20],['Catering',.32],['Cake & Gifts',.08],['Makeup / Entertainment',.12]]; ?><hr class="my-4"><h4>Suggested plan for <?=htmlspecialchars($plan['type'])?></h4><div class="table-responsive"><table class="table align-middle"><tbody><?php foreach($items as $it):$v=$b*$it[1];?><tr><td><?=htmlspecialchars($it[0])?></td><td class="text-end fw-bold">PKR <?=number_format($v)?></td></tr><?php endforeach;?></tbody><tfoot><tr><th>Estimated Total</th><th class="text-end">PKR <?=number_format($b)?></th></tr></tfoot></table></div><a href="budget-planner.php?plan_id=<?=$plan['id']?>" class="btn btn-outline-dark">Open Budget Planner</a> <a href="wedding-hub.php" class="btn btn-brand">Find Vendors</a><?php endif;?></div></div></div></div></section>
<?php include 'includes/footer.php'; ?>
