<?php
require_once 'includes/user-auth.php';
$id=(int)($_GET['id']??0); $stmt=$pdo->prepare("SELECT * FROM products WHERE id=?"); $stmt->execute([$id]); $product=$stmt->fetch();
if(!$product){http_response_code(404);exit('Product not found.');}
$errors=[];$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $name=trim($_POST['name']??'');$phone=trim($_POST['phone']??'');$email=trim($_POST['email']??'');$qty=max(1,(int)($_POST['quantity']??1));$address=trim($_POST['address']??'');$message=trim($_POST['message']??'');
 if($name===''||$phone===''||$address==='')$errors[]='Please complete your name, phone and delivery address.';
 if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Please enter a valid email.';
 if(!$errors){if((int)$product['stock']<$qty){$errors[]='The requested quantity is not currently available.';}else{$total=$qty*(float)$product['price'];$no='QCH-'.date('Ymd').'-'.str_pad((string)random_int(1,9999),4,'0',STR_PAD_LEFT);$q=$pdo->prepare("INSERT INTO orders(order_no,user_id,product_id,customer_name,phone,email,quantity,total,address,message) VALUES(?,?,?,?,?,?,?,?,?)");$q->execute([$no,$_SESSION['user_id']??null,$product['id'],$name,$phone,$email,$qty,$total,$address,$message]);$pdo->prepare('UPDATE products SET stock=stock-? WHERE id=?')->execute([$qty,$product['id']]);$pdo->prepare('INSERT INTO order_items(order_id,product_id,quantity,total) VALUES(?,?,?,?)')->execute([$pdo->lastInsertId(),$product['id'],$qty,$total]);$pdo->prepare('INSERT INTO notifications(title,message,type) VALUES(?,?,?)')->execute(['New product order',$no.' from '.$name,'order']);$success='Your order '.$no.' has been received successfully. We will contact you shortly.';}}
}
$pageTitle=$product['name'];$theme='gold';include 'includes/header.php';
?>
<section class="py-5"><div class="container"><div class="row g-5 align-items-start"><div class="col-lg-6"><img src="<?= htmlspecialchars($product['image']) ?>" class="w-100 rounded-4 shadow-sm" style="max-height:520px;object-fit:cover" alt="<?= htmlspecialchars($product['name']) ?>"></div><div class="col-lg-6"><span class="text-muted"><?= htmlspecialchars($product['category']) ?></span><h2 class="mt-2"><?= htmlspecialchars($product['name']) ?></h2><h3 class="price my-3">PKR <?= number_format((float)$product['price']) ?></h3><p><?= htmlspecialchars($product['description']) ?></p><div class="content-card p-4 mt-4"><h4>Place Your Order</h4><?php if($success): ?><div class="alert alert-success"><?= htmlspecialchars($success) ?></div><?php endif; ?><?php foreach($errors as $e): ?><div class="alert alert-danger"><?= htmlspecialchars($e) ?></div><?php endforeach; ?><form method="post" class="needs-validation" novalidate><div class="row g-3"><div class="col-md-6"><label class="form-label">Name *</label><input class="form-control" name="name" required></div><div class="col-md-6"><label class="form-label">Phone *</label><input class="form-control" name="phone" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email"></div><div class="col-md-6"><label class="form-label">Quantity *</label><input class="form-control" type="number" min="1" value="1" name="quantity" required></div><div class="col-12"><label class="form-label">Delivery Address *</label><textarea class="form-control" name="address" rows="3" required></textarea></div><div class="col-12"><label class="form-label">Message / Customization</label><textarea class="form-control" name="message" rows="2"></textarea></div><div class="col-12 d-grid"><button class="btn buy-now btn-lg"><i class="bi bi-bag-check-fill me-2"></i> Submit Order</button></div></div></form><a class="btn btn-outline-success w-100 mt-2 rounded-3" target="_blank" href="https://wa.me/923158118810?text=I%20want%20to%20order%20<?= urlencode($product['name']) ?>"><i class="bi bi-whatsapp me-1"></i> Order on WhatsApp</a></div></div></div></div></section>
<?php include 'includes/footer.php'; ?>
